
const actionTypes = {
    FETCH_WEATHER_DATA_REQUEST: "FETCH_WEATHER_DATA_REQUEST",
    FETCH_WEATHER_DATA_SUCCESS: "FETCH_WEATHER_DATA_SUCCESS",
    FETCH_WEATHER_DATA_FAILURE: "FETCH_WEATHER_DATA_FAILURE",
    GET_SPECIFIC_DAY: "GET_SPECIFIC_DAY",
    TOGGLE_TEMPERATURE_TYPE:'TOGGLE_TEMPERATURE_TYPE'
}

export default actionTypes